name: Python Package using Conda

on:
  pull_request:
    branches:
      - development
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.10 # Specify Python version if needed
        channels: conda-forge,defaults # Specify channels, conda-forge first

    - name: Install dependencies from environment.yml
      run: |
        conda create -y -n dronewq python=3.10 gdal conda-forge::zbar conda-forge::exiftool
        
    - name: Install conda deps
      run: conda run -n dronewq pip install -e .

    - name: Install hatch
      run: conda run -n dronewq pip install hatch

    - name: Test with pytest
      run: conda run -n dronewq hatch run test:run
    - name: Lint
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./src/dronewq --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./src/dronewq --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
